export const USER_OK = 'OK';
export const USER_ALREADY_EXISTS_CODE = 'USER_ALREADY_EXISTS';
export const USER_NOT_FOUND_CODE = 'USER_NOT_FOUND';
export const USER_INCORRECT_PASSWORD_CODE = 'USER_INCORRECT_PASSWORD';
